version: '3'
services:
    nginx:
        image: nginx:1.10
        volumes:
            - ./:/var/www
            - .docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8088:80
        links:
            - php
        networks:
            - app-net
    php:
        build:
            context: ./
            dockerfile: .docker/php/DockerFile
        volumes:
            - ./:/var/www
        links:
            - mysql
        networks:
            -  app-net
    mysql:
        image: mysql:5.7.22
        ports:
            - ${DOCKER_IP}4306:3306
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - project-wsd-mysql:/var/lib/mysql
        networks:
            -  app-net

networks:
    app-net:
        driver: bridge

volumes:
    project-wsd-mysql:
